// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4KECofGjMtRqNxEx9IY93oDqrjCz1trY',
    appId: '1:182573370795:web:a95557b08c1d25db78d6ee',
    messagingSenderId: '182573370795',
    projectId: 'evaluacion-app-dae11',
    authDomain: 'evaluacion-app-dae11.firebaseapp.com',
    databaseURL: 'https://evaluacion-app-dae11-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-app-dae11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTkRtMUGTbCgQXkL-MpZ9QjeTf3LVnFk',
    appId: '1:182573370795:android:d5d028349d1d2cb378d6ee',
    messagingSenderId: '182573370795',
    projectId: 'evaluacion-app-dae11',
    databaseURL: 'https://evaluacion-app-dae11-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-app-dae11.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4KECofGjMtRqNxEx9IY93oDqrjCz1trY',
    appId: '1:182573370795:web:7b158162d0d9aadf78d6ee',
    messagingSenderId: '182573370795',
    projectId: 'evaluacion-app-dae11',
    authDomain: 'evaluacion-app-dae11.firebaseapp.com',
    databaseURL: 'https://evaluacion-app-dae11-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-app-dae11.firebasestorage.app',
  );

}